### ISSUE TITLE
Upgrade mobile app version

### ISSUE THREAD

**Issue by Adrjnk** [dyrkin/luxmed-bot#52] opened 2023-12-02 09:40 UTC
Hi, could you upgrade version of mobile app?

`
Right(HttpResponse({"Errors":[{"ErrorCode":301,"Message":"Obecnie zainstalowana wersja aplikacji nie jest wspierana przez nowy system Portalu Pacjenta. Zaktualizuj aplikację do najnowszej wersji, aby móc z niej korzystać.","AdditionalData":{"ShopUrl":"itms-apps://apps.apple.com/pl/app/id552592684","FallbackUrl":"itms-apps://apps.apple.com/pl/app/id552592684","Title":"Zaktualizuj aplikację"}}]},409,HashMap(Transfer-Encoding -> Vector(chunked), Server -> Vector(Microsoft-IIS/10.0), Strict-Transport-Security -> Vector(max-age=31536000), Content-Encoding -> Vector(gzip), X-Iinfo -> Vector(9-2798158-2793398 pNYN RT(1701509473423 69) q(0 0 0 1) r(1 1) U6), Content-Type -> Vector(application/json), Date -> Vector(Sat, 02 Dec 2023 09:31:13 GMT), Set-Cookie -> Vector(visid_incap_2269135=cC+lJlKSR6ubhuci/jXlWGH5amUAAAAAQUIPAAAAAAA2SKKLJBPgGhifIHXFIYjW; expires=Sat, 30 Nov 2024 23:24:56 GMT; HttpOnly; path=/; Domain=.luxmed.pl; Secure; SameSite=None, incap_ses_1078_2269135=zvTxBW/cJWXJwNgbp9T1DmH5amUAAAAAhA5+lm3L6kGvqkwHs366MA==; path=/; Domain=.luxmed.pl; Secure; SameSite=None), X-CDN -> Vector(Imperva), X-Powered-By -> Vector(ASP.NET), Status -> Vector(HTTP/1.1 409 Conflict))))
Left(scalaj.http.HttpStatusException: 409 Error: HTTP/1.1 409 Conflict)
2023-12-02 10:31:14 c.l.s.service.ApiService - Call to remote api function has completed with result:
HttpRequest(https://portalpacjenta.luxmed.pl/PatientPortalMobileAPI/api/token,POST,FormBodyConnectFunc,List((client_id,iPhone), (grant_type,password), (password,******), (username,adrjnkm@gmail.com)),List((User-Agent,Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148), (accept-language,pl;q=1.0, pl;q=0.9, en;q=0.8), (Origin,https://portalpacjenta.luxmed.pl), (Custom-User-Agent,PatientPortal; 4.21.0; 12345678-3F3C-2C63-375B-BBA12392F44C; iOS; 16.3.0; iPhone14,5), (Accept,application/json, text/plain, */*), (Accept-Encoding,gzip, deflate, br), (User-Agent,Mozilla/5.0 (iPhone; CPU iPhone OS 16_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148), (Host,portalpacjenta.luxmed.pl), (Content-Type,application/x-www-form-urlencoded), (x-api-client-identifier,iPhone), (content-type,application/x-www-form-urlencoded)),List(scalaj.http.HttpOptions$$$Lambda$2482/0x0000000840e80040@6b60f991, scalaj.http.HttpOptions$$$Lambda$2483/0x0000000840e80840@570f9a7f, scalaj.http.HttpOptions$$$Lambda$2484/0x0000000840e81840@5b43f201),None,UTF-8,4096,PlainUrlFunc,true,None)
2023-12-02 10:31:14 com.lbs.api.http.package$ - Received response:
2023-12-02 10:31:14 com.lbs.api.http.package$ - Sending request:
2023-12-02 10:31:14 c.l.b.t.TelegramClient - Sending telegram request: SendMessage(Chat(5230276571),409 Error: HTTP/1.1 409 Conflict,Some(HTML),None,None,None,None,None,None,None)
`

**Comment by dyrkin** [comment] 2023-12-02 10:14
Hi. This is a duplicate of #52. It was fixed a day ago. Pull the latest version

**Closed by dyrkin** 2023-12-02 10:14 UTC
