### ISSUE TITLE
Luxmed Telegram bot doesnt work

### ISSUE THREAD

**Issue by GrzegorzCupial** [dyrkin/luxmed-bot#79] opened 2024-09-24 20:01 UTC
Telegram Luxmedbot doesnt return anything when any command e.g. /login or /accounts is used

**Comment by dyrkin** [comment] 2024-09-30 18:32
hey, could you check it again? i cannot reproduce

**Comment by dyrkin** [comment] 2024-10-01 19:29
Yeah, I restart it from time to time for different reason, so that could be the case :) closing this one

**Closed** 2024-10-01 19:29 UTC
